# coding: utf-8

# flake8: noqa

"""
    Radarr

    Radarr API docs

    The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.1.1" # x-release-please-version

# Define package exports
__all__ = [
    "AlternativeTitleApi",
    "ApiInfoApi",
    "AuthenticationApi",
    "AutoTaggingApi",
    "BackupApi",
    "BlocklistApi",
    "CalendarApi",
    "CalendarFeedApi",
    "CollectionApi",
    "CommandApi",
    "CreditApi",
    "CustomFilterApi",
    "CustomFormatApi",
    "DelayProfileApi",
    "DiskSpaceApi",
    "DownloadClientApi",
    "DownloadClientConfigApi",
    "ExtraFileApi",
    "FileSystemApi",
    "HealthApi",
    "HistoryApi",
    "HostConfigApi",
    "ImportExclusionsApi",
    "ImportListApi",
    "ImportListConfigApi",
    "ImportListMoviesApi",
    "IndexerApi",
    "IndexerConfigApi",
    "IndexerFlagApi",
    "LanguageApi",
    "LocalizationApi",
    "LogApi",
    "LogFileApi",
    "ManualImportApi",
    "MediaCoverApi",
    "MediaManagementConfigApi",
    "MetadataApi",
    "MetadataConfigApi",
    "MovieApi",
    "MovieEditorApi",
    "MovieFileApi",
    "MovieImportApi",
    "MovieLookupApi",
    "NamingConfigApi",
    "NotificationApi",
    "ParseApi",
    "PingApi",
    "QualityDefinitionApi",
    "QualityProfileApi",
    "QualityProfileSchemaApi",
    "QueueApi",
    "QueueActionApi",
    "QueueDetailsApi",
    "QueueStatusApi",
    "ReleaseApi",
    "ReleaseProfileApi",
    "ReleasePushApi",
    "RemotePathMappingApi",
    "RenameMovieApi",
    "RootFolderApi",
    "StaticResourceApi",
    "SystemApi",
    "TagApi",
    "TagDetailsApi",
    "TaskApi",
    "UiConfigApi",
    "UpdateApi",
    "UpdateLogFileApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddMovieMethod",
    "AddMovieOptions",
    "AlternativeTitleResource",
    "ApiInfoResource",
    "ApplyTags",
    "AuthenticationRequiredType",
    "AuthenticationType",
    "AutoTaggingResource",
    "AutoTaggingSpecificationSchema",
    "BackupResource",
    "BackupType",
    "BlocklistBulkResource",
    "BlocklistResource",
    "BlocklistResourcePagingResource",
    "CertificateValidationType",
    "CollectionMovieResource",
    "CollectionResource",
    "CollectionUpdateResource",
    "ColonReplacementFormat",
    "Command",
    "CommandPriority",
    "CommandResource",
    "CommandResult",
    "CommandStatus",
    "CommandTrigger",
    "ContractField",
    "CreditResource",
    "CreditType",
    "CustomFilterResource",
    "CustomFormatResource",
    "CustomFormatSpecificationSchema",
    "DatabaseType",
    "DelayProfileResource",
    "DiskSpaceResource",
    "DownloadClientBulkResource",
    "DownloadClientConfigResource",
    "DownloadClientResource",
    "DownloadProtocol",
    "ExtraFileResource",
    "ExtraFileType",
    "FileDateType",
    "HealthCheckResult",
    "HealthResource",
    "HistoryResource",
    "HistoryResourcePagingResource",
    "HostConfigResource",
    "ImportExclusionsResource",
    "ImportListBulkResource",
    "ImportListConfigResource",
    "ImportListResource",
    "ImportListType",
    "IndexerBulkResource",
    "IndexerConfigResource",
    "IndexerFlagResource",
    "IndexerResource",
    "Language",
    "LanguageResource",
    "LocalizationLanguageResource",
    "LogFileResource",
    "LogResource",
    "LogResourcePagingResource",
    "ManualImportReprocessResource",
    "ManualImportResource",
    "MediaCover",
    "MediaCoverTypes",
    "MediaInfoResource",
    "MediaManagementConfigResource",
    "MetadataConfigResource",
    "MetadataResource",
    "Modifier",
    "MonitorTypes",
    "MovieCollectionResource",
    "MovieEditorResource",
    "MovieFileListResource",
    "MovieFileResource",
    "MovieHistoryEventType",
    "MovieResource",
    "MovieRuntimeFormatType",
    "MovieStatisticsResource",
    "MovieStatusType",
    "NamingConfigResource",
    "NotificationResource",
    "ParseResource",
    "ParsedMovieInfo",
    "PingResource",
    "PrivacyLevel",
    "ProfileFormatItemResource",
    "ProperDownloadTypes",
    "ProviderMessage",
    "ProviderMessageType",
    "ProxyType",
    "Quality",
    "QualityDefinitionResource",
    "QualityModel",
    "QualityProfileQualityItemResource",
    "QualityProfileResource",
    "QualitySource",
    "QueueBulkResource",
    "QueueResource",
    "QueueResourcePagingResource",
    "QueueStatusResource",
    "RatingChild",
    "RatingType",
    "Ratings",
    "Rejection",
    "RejectionType",
    "ReleaseProfileResource",
    "ReleaseResource",
    "RemotePathMappingResource",
    "RenameMovieResource",
    "RescanAfterRefreshType",
    "Revision",
    "RootFolderResource",
    "RuntimeMode",
    "SelectOption",
    "SortDirection",
    "SourceType",
    "SystemResource",
    "TMDbCountryCode",
    "TagDetailsResource",
    "TagResource",
    "TaskResource",
    "TrackedDownloadState",
    "TrackedDownloadStatus",
    "TrackedDownloadStatusMessage",
    "UiConfigResource",
    "UnmappedFolder",
    "UpdateChanges",
    "UpdateMechanism",
    "UpdateResource",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from whisparr.api.alternative_title_api import AlternativeTitleApi as AlternativeTitleApi
    from whisparr.api.api_info_api import ApiInfoApi as ApiInfoApi
    from whisparr.api.authentication_api import AuthenticationApi as AuthenticationApi
    from whisparr.api.auto_tagging_api import AutoTaggingApi as AutoTaggingApi
    from whisparr.api.backup_api import BackupApi as BackupApi
    from whisparr.api.blocklist_api import BlocklistApi as BlocklistApi
    from whisparr.api.calendar_api import CalendarApi as CalendarApi
    from whisparr.api.calendar_feed_api import CalendarFeedApi as CalendarFeedApi
    from whisparr.api.collection_api import CollectionApi as CollectionApi
    from whisparr.api.command_api import CommandApi as CommandApi
    from whisparr.api.credit_api import CreditApi as CreditApi
    from whisparr.api.custom_filter_api import CustomFilterApi as CustomFilterApi
    from whisparr.api.custom_format_api import CustomFormatApi as CustomFormatApi
    from whisparr.api.delay_profile_api import DelayProfileApi as DelayProfileApi
    from whisparr.api.disk_space_api import DiskSpaceApi as DiskSpaceApi
    from whisparr.api.download_client_api import DownloadClientApi as DownloadClientApi
    from whisparr.api.download_client_config_api import DownloadClientConfigApi as DownloadClientConfigApi
    from whisparr.api.extra_file_api import ExtraFileApi as ExtraFileApi
    from whisparr.api.file_system_api import FileSystemApi as FileSystemApi
    from whisparr.api.health_api import HealthApi as HealthApi
    from whisparr.api.history_api import HistoryApi as HistoryApi
    from whisparr.api.host_config_api import HostConfigApi as HostConfigApi
    from whisparr.api.import_exclusions_api import ImportExclusionsApi as ImportExclusionsApi
    from whisparr.api.import_list_api import ImportListApi as ImportListApi
    from whisparr.api.import_list_config_api import ImportListConfigApi as ImportListConfigApi
    from whisparr.api.import_list_movies_api import ImportListMoviesApi as ImportListMoviesApi
    from whisparr.api.indexer_api import IndexerApi as IndexerApi
    from whisparr.api.indexer_config_api import IndexerConfigApi as IndexerConfigApi
    from whisparr.api.indexer_flag_api import IndexerFlagApi as IndexerFlagApi
    from whisparr.api.language_api import LanguageApi as LanguageApi
    from whisparr.api.localization_api import LocalizationApi as LocalizationApi
    from whisparr.api.log_api import LogApi as LogApi
    from whisparr.api.log_file_api import LogFileApi as LogFileApi
    from whisparr.api.manual_import_api import ManualImportApi as ManualImportApi
    from whisparr.api.media_cover_api import MediaCoverApi as MediaCoverApi
    from whisparr.api.media_management_config_api import MediaManagementConfigApi as MediaManagementConfigApi
    from whisparr.api.metadata_api import MetadataApi as MetadataApi
    from whisparr.api.metadata_config_api import MetadataConfigApi as MetadataConfigApi
    from whisparr.api.movie_api import MovieApi as MovieApi
    from whisparr.api.movie_editor_api import MovieEditorApi as MovieEditorApi
    from whisparr.api.movie_file_api import MovieFileApi as MovieFileApi
    from whisparr.api.movie_import_api import MovieImportApi as MovieImportApi
    from whisparr.api.movie_lookup_api import MovieLookupApi as MovieLookupApi
    from whisparr.api.naming_config_api import NamingConfigApi as NamingConfigApi
    from whisparr.api.notification_api import NotificationApi as NotificationApi
    from whisparr.api.parse_api import ParseApi as ParseApi
    from whisparr.api.ping_api import PingApi as PingApi
    from whisparr.api.quality_definition_api import QualityDefinitionApi as QualityDefinitionApi
    from whisparr.api.quality_profile_api import QualityProfileApi as QualityProfileApi
    from whisparr.api.quality_profile_schema_api import QualityProfileSchemaApi as QualityProfileSchemaApi
    from whisparr.api.queue_api import QueueApi as QueueApi
    from whisparr.api.queue_action_api import QueueActionApi as QueueActionApi
    from whisparr.api.queue_details_api import QueueDetailsApi as QueueDetailsApi
    from whisparr.api.queue_status_api import QueueStatusApi as QueueStatusApi
    from whisparr.api.release_api import ReleaseApi as ReleaseApi
    from whisparr.api.release_profile_api import ReleaseProfileApi as ReleaseProfileApi
    from whisparr.api.release_push_api import ReleasePushApi as ReleasePushApi
    from whisparr.api.remote_path_mapping_api import RemotePathMappingApi as RemotePathMappingApi
    from whisparr.api.rename_movie_api import RenameMovieApi as RenameMovieApi
    from whisparr.api.root_folder_api import RootFolderApi as RootFolderApi
    from whisparr.api.static_resource_api import StaticResourceApi as StaticResourceApi
    from whisparr.api.system_api import SystemApi as SystemApi
    from whisparr.api.tag_api import TagApi as TagApi
    from whisparr.api.tag_details_api import TagDetailsApi as TagDetailsApi
    from whisparr.api.task_api import TaskApi as TaskApi
    from whisparr.api.ui_config_api import UiConfigApi as UiConfigApi
    from whisparr.api.update_api import UpdateApi as UpdateApi
    from whisparr.api.update_log_file_api import UpdateLogFileApi as UpdateLogFileApi
    
    # import ApiClient
    from whisparr.api_response import ApiResponse as ApiResponse
    from whisparr.api_client import ApiClient as ApiClient
    from whisparr.configuration import Configuration as Configuration
    from whisparr.exceptions import OpenApiException as OpenApiException
    from whisparr.exceptions import ApiTypeError as ApiTypeError
    from whisparr.exceptions import ApiValueError as ApiValueError
    from whisparr.exceptions import ApiKeyError as ApiKeyError
    from whisparr.exceptions import ApiAttributeError as ApiAttributeError
    from whisparr.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from whisparr.models.add_movie_method import AddMovieMethod as AddMovieMethod
    from whisparr.models.add_movie_options import AddMovieOptions as AddMovieOptions
    from whisparr.models.alternative_title_resource import AlternativeTitleResource as AlternativeTitleResource
    from whisparr.models.api_info_resource import ApiInfoResource as ApiInfoResource
    from whisparr.models.apply_tags import ApplyTags as ApplyTags
    from whisparr.models.authentication_required_type import AuthenticationRequiredType as AuthenticationRequiredType
    from whisparr.models.authentication_type import AuthenticationType as AuthenticationType
    from whisparr.models.auto_tagging_resource import AutoTaggingResource as AutoTaggingResource
    from whisparr.models.auto_tagging_specification_schema import AutoTaggingSpecificationSchema as AutoTaggingSpecificationSchema
    from whisparr.models.backup_resource import BackupResource as BackupResource
    from whisparr.models.backup_type import BackupType as BackupType
    from whisparr.models.blocklist_bulk_resource import BlocklistBulkResource as BlocklistBulkResource
    from whisparr.models.blocklist_resource import BlocklistResource as BlocklistResource
    from whisparr.models.blocklist_resource_paging_resource import BlocklistResourcePagingResource as BlocklistResourcePagingResource
    from whisparr.models.certificate_validation_type import CertificateValidationType as CertificateValidationType
    from whisparr.models.collection_movie_resource import CollectionMovieResource as CollectionMovieResource
    from whisparr.models.collection_resource import CollectionResource as CollectionResource
    from whisparr.models.collection_update_resource import CollectionUpdateResource as CollectionUpdateResource
    from whisparr.models.colon_replacement_format import ColonReplacementFormat as ColonReplacementFormat
    from whisparr.models.command import Command as Command
    from whisparr.models.command_priority import CommandPriority as CommandPriority
    from whisparr.models.command_resource import CommandResource as CommandResource
    from whisparr.models.command_result import CommandResult as CommandResult
    from whisparr.models.command_status import CommandStatus as CommandStatus
    from whisparr.models.command_trigger import CommandTrigger as CommandTrigger
    from whisparr.models.contract_field import ContractField as ContractField
    from whisparr.models.credit_resource import CreditResource as CreditResource
    from whisparr.models.credit_type import CreditType as CreditType
    from whisparr.models.custom_filter_resource import CustomFilterResource as CustomFilterResource
    from whisparr.models.custom_format_resource import CustomFormatResource as CustomFormatResource
    from whisparr.models.custom_format_specification_schema import CustomFormatSpecificationSchema as CustomFormatSpecificationSchema
    from whisparr.models.database_type import DatabaseType as DatabaseType
    from whisparr.models.delay_profile_resource import DelayProfileResource as DelayProfileResource
    from whisparr.models.disk_space_resource import DiskSpaceResource as DiskSpaceResource
    from whisparr.models.download_client_bulk_resource import DownloadClientBulkResource as DownloadClientBulkResource
    from whisparr.models.download_client_config_resource import DownloadClientConfigResource as DownloadClientConfigResource
    from whisparr.models.download_client_resource import DownloadClientResource as DownloadClientResource
    from whisparr.models.download_protocol import DownloadProtocol as DownloadProtocol
    from whisparr.models.extra_file_resource import ExtraFileResource as ExtraFileResource
    from whisparr.models.extra_file_type import ExtraFileType as ExtraFileType
    from whisparr.models.file_date_type import FileDateType as FileDateType
    from whisparr.models.health_check_result import HealthCheckResult as HealthCheckResult
    from whisparr.models.health_resource import HealthResource as HealthResource
    from whisparr.models.history_resource import HistoryResource as HistoryResource
    from whisparr.models.history_resource_paging_resource import HistoryResourcePagingResource as HistoryResourcePagingResource
    from whisparr.models.host_config_resource import HostConfigResource as HostConfigResource
    from whisparr.models.import_exclusions_resource import ImportExclusionsResource as ImportExclusionsResource
    from whisparr.models.import_list_bulk_resource import ImportListBulkResource as ImportListBulkResource
    from whisparr.models.import_list_config_resource import ImportListConfigResource as ImportListConfigResource
    from whisparr.models.import_list_resource import ImportListResource as ImportListResource
    from whisparr.models.import_list_type import ImportListType as ImportListType
    from whisparr.models.indexer_bulk_resource import IndexerBulkResource as IndexerBulkResource
    from whisparr.models.indexer_config_resource import IndexerConfigResource as IndexerConfigResource
    from whisparr.models.indexer_flag_resource import IndexerFlagResource as IndexerFlagResource
    from whisparr.models.indexer_resource import IndexerResource as IndexerResource
    from whisparr.models.language import Language as Language
    from whisparr.models.language_resource import LanguageResource as LanguageResource
    from whisparr.models.localization_language_resource import LocalizationLanguageResource as LocalizationLanguageResource
    from whisparr.models.log_file_resource import LogFileResource as LogFileResource
    from whisparr.models.log_resource import LogResource as LogResource
    from whisparr.models.log_resource_paging_resource import LogResourcePagingResource as LogResourcePagingResource
    from whisparr.models.manual_import_reprocess_resource import ManualImportReprocessResource as ManualImportReprocessResource
    from whisparr.models.manual_import_resource import ManualImportResource as ManualImportResource
    from whisparr.models.media_cover import MediaCover as MediaCover
    from whisparr.models.media_cover_types import MediaCoverTypes as MediaCoverTypes
    from whisparr.models.media_info_resource import MediaInfoResource as MediaInfoResource
    from whisparr.models.media_management_config_resource import MediaManagementConfigResource as MediaManagementConfigResource
    from whisparr.models.metadata_config_resource import MetadataConfigResource as MetadataConfigResource
    from whisparr.models.metadata_resource import MetadataResource as MetadataResource
    from whisparr.models.modifier import Modifier as Modifier
    from whisparr.models.monitor_types import MonitorTypes as MonitorTypes
    from whisparr.models.movie_collection_resource import MovieCollectionResource as MovieCollectionResource
    from whisparr.models.movie_editor_resource import MovieEditorResource as MovieEditorResource
    from whisparr.models.movie_file_list_resource import MovieFileListResource as MovieFileListResource
    from whisparr.models.movie_file_resource import MovieFileResource as MovieFileResource
    from whisparr.models.movie_history_event_type import MovieHistoryEventType as MovieHistoryEventType
    from whisparr.models.movie_resource import MovieResource as MovieResource
    from whisparr.models.movie_runtime_format_type import MovieRuntimeFormatType as MovieRuntimeFormatType
    from whisparr.models.movie_statistics_resource import MovieStatisticsResource as MovieStatisticsResource
    from whisparr.models.movie_status_type import MovieStatusType as MovieStatusType
    from whisparr.models.naming_config_resource import NamingConfigResource as NamingConfigResource
    from whisparr.models.notification_resource import NotificationResource as NotificationResource
    from whisparr.models.parse_resource import ParseResource as ParseResource
    from whisparr.models.parsed_movie_info import ParsedMovieInfo as ParsedMovieInfo
    from whisparr.models.ping_resource import PingResource as PingResource
    from whisparr.models.privacy_level import PrivacyLevel as PrivacyLevel
    from whisparr.models.profile_format_item_resource import ProfileFormatItemResource as ProfileFormatItemResource
    from whisparr.models.proper_download_types import ProperDownloadTypes as ProperDownloadTypes
    from whisparr.models.provider_message import ProviderMessage as ProviderMessage
    from whisparr.models.provider_message_type import ProviderMessageType as ProviderMessageType
    from whisparr.models.proxy_type import ProxyType as ProxyType
    from whisparr.models.quality import Quality as Quality
    from whisparr.models.quality_definition_resource import QualityDefinitionResource as QualityDefinitionResource
    from whisparr.models.quality_model import QualityModel as QualityModel
    from whisparr.models.quality_profile_quality_item_resource import QualityProfileQualityItemResource as QualityProfileQualityItemResource
    from whisparr.models.quality_profile_resource import QualityProfileResource as QualityProfileResource
    from whisparr.models.quality_source import QualitySource as QualitySource
    from whisparr.models.queue_bulk_resource import QueueBulkResource as QueueBulkResource
    from whisparr.models.queue_resource import QueueResource as QueueResource
    from whisparr.models.queue_resource_paging_resource import QueueResourcePagingResource as QueueResourcePagingResource
    from whisparr.models.queue_status_resource import QueueStatusResource as QueueStatusResource
    from whisparr.models.rating_child import RatingChild as RatingChild
    from whisparr.models.rating_type import RatingType as RatingType
    from whisparr.models.ratings import Ratings as Ratings
    from whisparr.models.rejection import Rejection as Rejection
    from whisparr.models.rejection_type import RejectionType as RejectionType
    from whisparr.models.release_profile_resource import ReleaseProfileResource as ReleaseProfileResource
    from whisparr.models.release_resource import ReleaseResource as ReleaseResource
    from whisparr.models.remote_path_mapping_resource import RemotePathMappingResource as RemotePathMappingResource
    from whisparr.models.rename_movie_resource import RenameMovieResource as RenameMovieResource
    from whisparr.models.rescan_after_refresh_type import RescanAfterRefreshType as RescanAfterRefreshType
    from whisparr.models.revision import Revision as Revision
    from whisparr.models.root_folder_resource import RootFolderResource as RootFolderResource
    from whisparr.models.runtime_mode import RuntimeMode as RuntimeMode
    from whisparr.models.select_option import SelectOption as SelectOption
    from whisparr.models.sort_direction import SortDirection as SortDirection
    from whisparr.models.source_type import SourceType as SourceType
    from whisparr.models.system_resource import SystemResource as SystemResource
    from whisparr.models.tmdb_country_code import TMDbCountryCode as TMDbCountryCode
    from whisparr.models.tag_details_resource import TagDetailsResource as TagDetailsResource
    from whisparr.models.tag_resource import TagResource as TagResource
    from whisparr.models.task_resource import TaskResource as TaskResource
    from whisparr.models.tracked_download_state import TrackedDownloadState as TrackedDownloadState
    from whisparr.models.tracked_download_status import TrackedDownloadStatus as TrackedDownloadStatus
    from whisparr.models.tracked_download_status_message import TrackedDownloadStatusMessage as TrackedDownloadStatusMessage
    from whisparr.models.ui_config_resource import UiConfigResource as UiConfigResource
    from whisparr.models.unmapped_folder import UnmappedFolder as UnmappedFolder
    from whisparr.models.update_changes import UpdateChanges as UpdateChanges
    from whisparr.models.update_mechanism import UpdateMechanism as UpdateMechanism
    from whisparr.models.update_resource import UpdateResource as UpdateResource
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from whisparr.api.alternative_title_api import AlternativeTitleApi as AlternativeTitleApi
from whisparr.api.api_info_api import ApiInfoApi as ApiInfoApi
from whisparr.api.authentication_api import AuthenticationApi as AuthenticationApi
from whisparr.api.auto_tagging_api import AutoTaggingApi as AutoTaggingApi
from whisparr.api.backup_api import BackupApi as BackupApi
from whisparr.api.blocklist_api import BlocklistApi as BlocklistApi
from whisparr.api.calendar_api import CalendarApi as CalendarApi
from whisparr.api.calendar_feed_api import CalendarFeedApi as CalendarFeedApi
from whisparr.api.collection_api import CollectionApi as CollectionApi
from whisparr.api.command_api import CommandApi as CommandApi
from whisparr.api.credit_api import CreditApi as CreditApi
from whisparr.api.custom_filter_api import CustomFilterApi as CustomFilterApi
from whisparr.api.custom_format_api import CustomFormatApi as CustomFormatApi
from whisparr.api.delay_profile_api import DelayProfileApi as DelayProfileApi
from whisparr.api.disk_space_api import DiskSpaceApi as DiskSpaceApi
from whisparr.api.download_client_api import DownloadClientApi as DownloadClientApi
from whisparr.api.download_client_config_api import DownloadClientConfigApi as DownloadClientConfigApi
from whisparr.api.extra_file_api import ExtraFileApi as ExtraFileApi
from whisparr.api.file_system_api import FileSystemApi as FileSystemApi
from whisparr.api.health_api import HealthApi as HealthApi
from whisparr.api.history_api import HistoryApi as HistoryApi
from whisparr.api.host_config_api import HostConfigApi as HostConfigApi
from whisparr.api.import_exclusions_api import ImportExclusionsApi as ImportExclusionsApi
from whisparr.api.import_list_api import ImportListApi as ImportListApi
from whisparr.api.import_list_config_api import ImportListConfigApi as ImportListConfigApi
from whisparr.api.import_list_movies_api import ImportListMoviesApi as ImportListMoviesApi
from whisparr.api.indexer_api import IndexerApi as IndexerApi
from whisparr.api.indexer_config_api import IndexerConfigApi as IndexerConfigApi
from whisparr.api.indexer_flag_api import IndexerFlagApi as IndexerFlagApi
from whisparr.api.language_api import LanguageApi as LanguageApi
from whisparr.api.localization_api import LocalizationApi as LocalizationApi
from whisparr.api.log_api import LogApi as LogApi
from whisparr.api.log_file_api import LogFileApi as LogFileApi
from whisparr.api.manual_import_api import ManualImportApi as ManualImportApi
from whisparr.api.media_cover_api import MediaCoverApi as MediaCoverApi
from whisparr.api.media_management_config_api import MediaManagementConfigApi as MediaManagementConfigApi
from whisparr.api.metadata_api import MetadataApi as MetadataApi
from whisparr.api.metadata_config_api import MetadataConfigApi as MetadataConfigApi
from whisparr.api.movie_api import MovieApi as MovieApi
from whisparr.api.movie_editor_api import MovieEditorApi as MovieEditorApi
from whisparr.api.movie_file_api import MovieFileApi as MovieFileApi
from whisparr.api.movie_import_api import MovieImportApi as MovieImportApi
from whisparr.api.movie_lookup_api import MovieLookupApi as MovieLookupApi
from whisparr.api.naming_config_api import NamingConfigApi as NamingConfigApi
from whisparr.api.notification_api import NotificationApi as NotificationApi
from whisparr.api.parse_api import ParseApi as ParseApi
from whisparr.api.ping_api import PingApi as PingApi
from whisparr.api.quality_definition_api import QualityDefinitionApi as QualityDefinitionApi
from whisparr.api.quality_profile_api import QualityProfileApi as QualityProfileApi
from whisparr.api.quality_profile_schema_api import QualityProfileSchemaApi as QualityProfileSchemaApi
from whisparr.api.queue_api import QueueApi as QueueApi
from whisparr.api.queue_action_api import QueueActionApi as QueueActionApi
from whisparr.api.queue_details_api import QueueDetailsApi as QueueDetailsApi
from whisparr.api.queue_status_api import QueueStatusApi as QueueStatusApi
from whisparr.api.release_api import ReleaseApi as ReleaseApi
from whisparr.api.release_profile_api import ReleaseProfileApi as ReleaseProfileApi
from whisparr.api.release_push_api import ReleasePushApi as ReleasePushApi
from whisparr.api.remote_path_mapping_api import RemotePathMappingApi as RemotePathMappingApi
from whisparr.api.rename_movie_api import RenameMovieApi as RenameMovieApi
from whisparr.api.root_folder_api import RootFolderApi as RootFolderApi
from whisparr.api.static_resource_api import StaticResourceApi as StaticResourceApi
from whisparr.api.system_api import SystemApi as SystemApi
from whisparr.api.tag_api import TagApi as TagApi
from whisparr.api.tag_details_api import TagDetailsApi as TagDetailsApi
from whisparr.api.task_api import TaskApi as TaskApi
from whisparr.api.ui_config_api import UiConfigApi as UiConfigApi
from whisparr.api.update_api import UpdateApi as UpdateApi
from whisparr.api.update_log_file_api import UpdateLogFileApi as UpdateLogFileApi

# import ApiClient
from whisparr.api_response import ApiResponse as ApiResponse
from whisparr.api_client import ApiClient as ApiClient
from whisparr.configuration import Configuration as Configuration
from whisparr.exceptions import OpenApiException as OpenApiException
from whisparr.exceptions import ApiTypeError as ApiTypeError
from whisparr.exceptions import ApiValueError as ApiValueError
from whisparr.exceptions import ApiKeyError as ApiKeyError
from whisparr.exceptions import ApiAttributeError as ApiAttributeError
from whisparr.exceptions import ApiException as ApiException

# import models into sdk package
from whisparr.models.add_movie_method import AddMovieMethod as AddMovieMethod
from whisparr.models.add_movie_options import AddMovieOptions as AddMovieOptions
from whisparr.models.alternative_title_resource import AlternativeTitleResource as AlternativeTitleResource
from whisparr.models.api_info_resource import ApiInfoResource as ApiInfoResource
from whisparr.models.apply_tags import ApplyTags as ApplyTags
from whisparr.models.authentication_required_type import AuthenticationRequiredType as AuthenticationRequiredType
from whisparr.models.authentication_type import AuthenticationType as AuthenticationType
from whisparr.models.auto_tagging_resource import AutoTaggingResource as AutoTaggingResource
from whisparr.models.auto_tagging_specification_schema import AutoTaggingSpecificationSchema as AutoTaggingSpecificationSchema
from whisparr.models.backup_resource import BackupResource as BackupResource
from whisparr.models.backup_type import BackupType as BackupType
from whisparr.models.blocklist_bulk_resource import BlocklistBulkResource as BlocklistBulkResource
from whisparr.models.blocklist_resource import BlocklistResource as BlocklistResource
from whisparr.models.blocklist_resource_paging_resource import BlocklistResourcePagingResource as BlocklistResourcePagingResource
from whisparr.models.certificate_validation_type import CertificateValidationType as CertificateValidationType
from whisparr.models.collection_movie_resource import CollectionMovieResource as CollectionMovieResource
from whisparr.models.collection_resource import CollectionResource as CollectionResource
from whisparr.models.collection_update_resource import CollectionUpdateResource as CollectionUpdateResource
from whisparr.models.colon_replacement_format import ColonReplacementFormat as ColonReplacementFormat
from whisparr.models.command import Command as Command
from whisparr.models.command_priority import CommandPriority as CommandPriority
from whisparr.models.command_resource import CommandResource as CommandResource
from whisparr.models.command_result import CommandResult as CommandResult
from whisparr.models.command_status import CommandStatus as CommandStatus
from whisparr.models.command_trigger import CommandTrigger as CommandTrigger
from whisparr.models.contract_field import ContractField as ContractField
from whisparr.models.credit_resource import CreditResource as CreditResource
from whisparr.models.credit_type import CreditType as CreditType
from whisparr.models.custom_filter_resource import CustomFilterResource as CustomFilterResource
from whisparr.models.custom_format_resource import CustomFormatResource as CustomFormatResource
from whisparr.models.custom_format_specification_schema import CustomFormatSpecificationSchema as CustomFormatSpecificationSchema
from whisparr.models.database_type import DatabaseType as DatabaseType
from whisparr.models.delay_profile_resource import DelayProfileResource as DelayProfileResource
from whisparr.models.disk_space_resource import DiskSpaceResource as DiskSpaceResource
from whisparr.models.download_client_bulk_resource import DownloadClientBulkResource as DownloadClientBulkResource
from whisparr.models.download_client_config_resource import DownloadClientConfigResource as DownloadClientConfigResource
from whisparr.models.download_client_resource import DownloadClientResource as DownloadClientResource
from whisparr.models.download_protocol import DownloadProtocol as DownloadProtocol
from whisparr.models.extra_file_resource import ExtraFileResource as ExtraFileResource
from whisparr.models.extra_file_type import ExtraFileType as ExtraFileType
from whisparr.models.file_date_type import FileDateType as FileDateType
from whisparr.models.health_check_result import HealthCheckResult as HealthCheckResult
from whisparr.models.health_resource import HealthResource as HealthResource
from whisparr.models.history_resource import HistoryResource as HistoryResource
from whisparr.models.history_resource_paging_resource import HistoryResourcePagingResource as HistoryResourcePagingResource
from whisparr.models.host_config_resource import HostConfigResource as HostConfigResource
from whisparr.models.import_exclusions_resource import ImportExclusionsResource as ImportExclusionsResource
from whisparr.models.import_list_bulk_resource import ImportListBulkResource as ImportListBulkResource
from whisparr.models.import_list_config_resource import ImportListConfigResource as ImportListConfigResource
from whisparr.models.import_list_resource import ImportListResource as ImportListResource
from whisparr.models.import_list_type import ImportListType as ImportListType
from whisparr.models.indexer_bulk_resource import IndexerBulkResource as IndexerBulkResource
from whisparr.models.indexer_config_resource import IndexerConfigResource as IndexerConfigResource
from whisparr.models.indexer_flag_resource import IndexerFlagResource as IndexerFlagResource
from whisparr.models.indexer_resource import IndexerResource as IndexerResource
from whisparr.models.language import Language as Language
from whisparr.models.language_resource import LanguageResource as LanguageResource
from whisparr.models.localization_language_resource import LocalizationLanguageResource as LocalizationLanguageResource
from whisparr.models.log_file_resource import LogFileResource as LogFileResource
from whisparr.models.log_resource import LogResource as LogResource
from whisparr.models.log_resource_paging_resource import LogResourcePagingResource as LogResourcePagingResource
from whisparr.models.manual_import_reprocess_resource import ManualImportReprocessResource as ManualImportReprocessResource
from whisparr.models.manual_import_resource import ManualImportResource as ManualImportResource
from whisparr.models.media_cover import MediaCover as MediaCover
from whisparr.models.media_cover_types import MediaCoverTypes as MediaCoverTypes
from whisparr.models.media_info_resource import MediaInfoResource as MediaInfoResource
from whisparr.models.media_management_config_resource import MediaManagementConfigResource as MediaManagementConfigResource
from whisparr.models.metadata_config_resource import MetadataConfigResource as MetadataConfigResource
from whisparr.models.metadata_resource import MetadataResource as MetadataResource
from whisparr.models.modifier import Modifier as Modifier
from whisparr.models.monitor_types import MonitorTypes as MonitorTypes
from whisparr.models.movie_collection_resource import MovieCollectionResource as MovieCollectionResource
from whisparr.models.movie_editor_resource import MovieEditorResource as MovieEditorResource
from whisparr.models.movie_file_list_resource import MovieFileListResource as MovieFileListResource
from whisparr.models.movie_file_resource import MovieFileResource as MovieFileResource
from whisparr.models.movie_history_event_type import MovieHistoryEventType as MovieHistoryEventType
from whisparr.models.movie_resource import MovieResource as MovieResource
from whisparr.models.movie_runtime_format_type import MovieRuntimeFormatType as MovieRuntimeFormatType
from whisparr.models.movie_statistics_resource import MovieStatisticsResource as MovieStatisticsResource
from whisparr.models.movie_status_type import MovieStatusType as MovieStatusType
from whisparr.models.naming_config_resource import NamingConfigResource as NamingConfigResource
from whisparr.models.notification_resource import NotificationResource as NotificationResource
from whisparr.models.parse_resource import ParseResource as ParseResource
from whisparr.models.parsed_movie_info import ParsedMovieInfo as ParsedMovieInfo
from whisparr.models.ping_resource import PingResource as PingResource
from whisparr.models.privacy_level import PrivacyLevel as PrivacyLevel
from whisparr.models.profile_format_item_resource import ProfileFormatItemResource as ProfileFormatItemResource
from whisparr.models.proper_download_types import ProperDownloadTypes as ProperDownloadTypes
from whisparr.models.provider_message import ProviderMessage as ProviderMessage
from whisparr.models.provider_message_type import ProviderMessageType as ProviderMessageType
from whisparr.models.proxy_type import ProxyType as ProxyType
from whisparr.models.quality import Quality as Quality
from whisparr.models.quality_definition_resource import QualityDefinitionResource as QualityDefinitionResource
from whisparr.models.quality_model import QualityModel as QualityModel
from whisparr.models.quality_profile_quality_item_resource import QualityProfileQualityItemResource as QualityProfileQualityItemResource
from whisparr.models.quality_profile_resource import QualityProfileResource as QualityProfileResource
from whisparr.models.quality_source import QualitySource as QualitySource
from whisparr.models.queue_bulk_resource import QueueBulkResource as QueueBulkResource
from whisparr.models.queue_resource import QueueResource as QueueResource
from whisparr.models.queue_resource_paging_resource import QueueResourcePagingResource as QueueResourcePagingResource
from whisparr.models.queue_status_resource import QueueStatusResource as QueueStatusResource
from whisparr.models.rating_child import RatingChild as RatingChild
from whisparr.models.rating_type import RatingType as RatingType
from whisparr.models.ratings import Ratings as Ratings
from whisparr.models.rejection import Rejection as Rejection
from whisparr.models.rejection_type import RejectionType as RejectionType
from whisparr.models.release_profile_resource import ReleaseProfileResource as ReleaseProfileResource
from whisparr.models.release_resource import ReleaseResource as ReleaseResource
from whisparr.models.remote_path_mapping_resource import RemotePathMappingResource as RemotePathMappingResource
from whisparr.models.rename_movie_resource import RenameMovieResource as RenameMovieResource
from whisparr.models.rescan_after_refresh_type import RescanAfterRefreshType as RescanAfterRefreshType
from whisparr.models.revision import Revision as Revision
from whisparr.models.root_folder_resource import RootFolderResource as RootFolderResource
from whisparr.models.runtime_mode import RuntimeMode as RuntimeMode
from whisparr.models.select_option import SelectOption as SelectOption
from whisparr.models.sort_direction import SortDirection as SortDirection
from whisparr.models.source_type import SourceType as SourceType
from whisparr.models.system_resource import SystemResource as SystemResource
from whisparr.models.tmdb_country_code import TMDbCountryCode as TMDbCountryCode
from whisparr.models.tag_details_resource import TagDetailsResource as TagDetailsResource
from whisparr.models.tag_resource import TagResource as TagResource
from whisparr.models.task_resource import TaskResource as TaskResource
from whisparr.models.tracked_download_state import TrackedDownloadState as TrackedDownloadState
from whisparr.models.tracked_download_status import TrackedDownloadStatus as TrackedDownloadStatus
from whisparr.models.tracked_download_status_message import TrackedDownloadStatusMessage as TrackedDownloadStatusMessage
from whisparr.models.ui_config_resource import UiConfigResource as UiConfigResource
from whisparr.models.unmapped_folder import UnmappedFolder as UnmappedFolder
from whisparr.models.update_changes import UpdateChanges as UpdateChanges
from whisparr.models.update_mechanism import UpdateMechanism as UpdateMechanism
from whisparr.models.update_resource import UpdateResource as UpdateResource

""",
            name=__name__,
            doc=__doc__,
        )
    )
